name: GoFmt Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  gofmt:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Check code formatting
      run: gofmt -l .