name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build project
      run: go build -o nexarun .

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./nexarun
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}